# Generated by cucumber-sinatra. (2014-10-06 11:14:35 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/bookmarker.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = BookMarker

class BookMarkerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BookMarkerWorld.new
end
